image: ghdl/ghdl:buster-mcode

variables:
  GIT_DEPTH: 1

stages:
  - build

build-job:
  stage: build
  script:
    - cd hardware
    - make -f ghdl.mk compile
  only:
    changes:
      - hardware/src/**/*.vhd