image: ghdl/ghdl:buster-mcode

variables:
  GIT_DEPTH: 1

stages:
  - build

build-job:
  stage: build
  script:
    - cd hardware
    - make ghdl
  only:
    changes:
      - /**/*.vhd
      - .gitlab-ci.yml